version: "3.8"

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy

  blog-app-back:
    image: blog-app-backend-prod
    build:
      context: ./Part4_BlogListAppServer
      dockerfile: ./Part4_BlogListAppServer/dev.Dockerfile
    volumes:
      - ./Part4_BlogListAppServer:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3001

  blog-app-front:
    image: blog-app-frontend-prod
    build:
      context: ./part5-blog-app-client
      dockerfile: ./part5-blog-app-client/dev.Dockerfile
    volumes:
      - ./part5-blog-app-client:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true